# Jekyll Configuration
title: Sitemap Test Website
description: A test website to demonstrate Jekyll sitemap generation
url: "https://valentinaapetrova.github.io"
baseurl: "/SitemapTest"

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-last-modified-at

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Permalink settings
permalink: /:year/:month/:day/:title/
